# Generated by Django 2.2 on 2021-07-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=20, verbose_name='汇报人')),
                ('report_date', models.DateField(verbose_name='周报日期')),
                ('report_redflag', models.CharField(max_length=200)),
                ('report_achievements', models.CharField(max_length=1000)),
                ('report_supportNeeded', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户姓名')),
                ('user_password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
