# Generated by Django 2.2 on 2021-07-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyReport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
